### ISSUE TITLE
File gets locked even after pausing when completed 

### ISSUE THREAD

**Issue by doesDeveloper** [ikatson/rqbit#120]
After the download is complete, I pause the torrent, but the files remain locked and unusable, displaying a message that they are being used in another program. The issue resolves only when I forget the torrent.
Am I missing something or I have to always remove torrent to use the files?

**Comment by ikatson** [comment]
I don't have a Windows box, so I asked a friend to check, they said it works on 5.6.0 no problem - you can open the file while it's being downloaded and while it's on pause.

**Comment by ikatson** [comment]
Just checked on a Windows 11 VM and 5.6.0 - I can open and even delete the files while rqbit uses them

**Comment by ikatson** [comment]
Closing unless more info is provided on how to repro (OS etc)
