### ISSUE TITLE
Nested directories have incorrect names in the desktop app

### ISSUE THREAD

**Issue by DCNick3** [ikatson/rqbit#121]
All the second level nested directories (like `torrent name/directory/inner directory/`) all have the same name as the root directory (torrent name).

```
$ tree torrent\ name/
torrent name/
└── directory
    └── inner directory
        └── uwu.txt

3 directories, 1 file
```
![image](https://github.com/ikatson/rqbit/assets/10363282/79c3f039-86d4-4a11-8fb5-977df89ec34d)

^ the second-level directory should be called `inner directory`, not just `directory`

Here's a repro torrent: [torrent name.zip](https://github.com/ikatson/rqbit/files/15026094/torrent.name.zip)

I think the problem is in this line: https://github.com/ikatson/rqbit/commit/b289f1eeaa622db78092f92a41ec7c8854165603#diff-5d9f6d13b4676145182d9282de15b133d5ba54d1c6dc8d4693f04397d91fc703R43

Before the change the `name` pushed was taken from the output of the `splitOnce` function, and, therefore, was always stripping one component off the filename. But now the file object is pushed as-is and the first component is always taken as the group key.

I think using `depth` instead of `0` might be a simple fix for this

**Comment by ikatson** [comment]
Thanks for the bug and finding the cause! This should be easy to fix, I'll do that soon
