### ISSUE TITLE
How to scrape torrents?

### ISSUE THREAD

**Issue by dessalines** [ikatson/rqbit#13]
I have a list of torrent infohashes, and a list of trackers. Can I use rqbit to scrape these to get update seeder / leecher counts?

**Comment by ikatson** [comment]
Not with the rqbit main binary, but you can do that using librqbit

```Dht::new().await.get_peers(info_hash)``` will get you a stream of peers for that infohash.

For how to query a tracker, see the implementations of ```async fn single_tracker_monitor(&self, mut tracker_url: Url)``` and ```async fn tracker_one_request(&self, tracker_url: Url)```.
In short, you need to create a TrackerRequest, make a querystring out of it, and append it to tracker URL. Then using any HTTP client, call it, and deserialize into TrackerResponse (using bencode), it will contain the peers.

**Comment by dessalines** [comment]
AFAIK a lot of torrent clients batch their requests to trackers, so a single request to a tracker might have tons of infohashes. Is that possible?

My use case, is that I have **a lot** of torrents I need to periodically fetch updated seeder / eecher counts for.

I'm trying to migrate from a javascript library that does this. I give it a list of infohashes, and a list of tracker announce urls, and it aggregates the data, and gives me the highest seeder, leecher, and completed counts for each of them in JSON.

**Comment by ikatson** [comment]
From what I see, the tracker protocol supports only one info hash at a time, i.e. doesn't support batching.
See 
TCP / HTTP: https://wiki.theory.org/BitTorrent_Tracker_Protocol
and UDP (rqbit doesn't support this) https://www.bittorrent.org/beps/bep_0015.html

**Comment by dessalines** [comment]
https://wiki.vuze.com/w/Scrape

Section is called, multi-hash scrape.

**Comment by ikatson** [comment]
Ah got it. Well, there's no such feature in rqbit. But this seems like a separate HTTP API (scrape) vs the regular announce. You can just implement it yourself, and deserialize with bencode to do what you need.
