### ISSUE TITLE
Feature request: Download torrent content sequentially

### ISSUE THREAD

**Issue by cocool97** [ikatson/rqbit#134]
Feature request already discussed in a previous issue, adding the possibility via an option to download the content of a torrent sequentially. (Meaning asking blocks in order, from start to end). This would allow me to write and release my torrent streaming server with all cool new features added in v6.0.0 !

**Comment by ikatson** [comment]
Hmm, but this should be the case already. The blocks are already requested sequentially. But you can't guarantee how peers send them back. 

E.g. we may ask peer 1 for blocks 1-128, and peer 2 for blocks 128-256, but peer 2 might be faster to respond.

However if peer 1 is 10 times slower than a faster peer then the faster peer will steal blocks form the slow peer.
