### ISSUE TITLE
limit parallel checking of torrents

### ISSUE THREAD

**Issue by milahu** [ikatson/rqbit#139]
currently there seems to be no limit, all torrents are checked in parallel

cpu load is about 25% when checking 20 torrents in parallel
so this is just slow, not causing too much cpu load

libtorrent has the setting [hashing_threads](https://www.libtorrent.org/reference-Settings.html#hashing_threads)

aka: limit number of checking threads

**Comment by ikatson** [comment]
There's probably a limit - the number of tokio IO worker threads. It's used for other things too though like writing to disk.
It's configurable from command line too: https://github.com/ikatson/rqbit/blob/main/crates/rqbit/src/main.rs#L105

Does that help?

**Comment by milahu** [comment]
> tokio IO worker threads

too generic. hashing threads produce more CPU load

in this case, serial processing is better, because checked torrents are ready for seeding
