### ISSUE TITLE
request: exit program when download is complete

### ISSUE THREAD

**Issue by MatthewCroughan** [ikatson/rqbit#14]
This is a great program. It would be even better if I could use it like a one-time like via `wget` or `curl`, like [aria2c](https://aria2.github.io/) allows. It would also be nice to allow only downloads without seeding. This allows use-cases such as using rqbit in a CI pipeline, and for automation, where bittorrent is just a transfer mechanism for self-hosted files! I love it.

**Comment by ikatson** [comment]
Thanks for kind words, and glad to know it's working well for you! And it's a pleasant surprise someone packaged it for nixOS. When I created rqbit initially, this feature was one of my todos, and I even added a bit of support code to put it in but never ended up implementing as far as I remember.

I'll try take a look at how costly will this be to add, and if/when I do I'll update this issue

**Comment by IgnisDa** [comment]
@ikatson Would really love this feature. Any plans for this?

**Comment by ikatson** [comment]
Added this feature @IgnisDa @MatthewCroughan 
Flag "--exit-on-download" or short "-e".

Usage
```
reqbit download -o /tmp/ubuntu/ --exit-on-download 'https://releases.ubuntu.com/20.04/ubuntu-20.04.6-live-server-amd64.iso.torrent'
```

This should be present in 2.2.0 release that github is compiling now
