### ISSUE TITLE
Move HTTP API server out of librqbit

### ISSUE THREAD

**Issue by The-Minecraft-Scientist** [ikatson/rqbit#141]
Currently if I add librqbit to my project it pulls in a ton of massive dependencies (axum and co) required to run the web API. Ideally the crate on crates.io would contain the minimal number of dependencies required to download torrents via rust functions (i.e. using the `Session` API). I might make a PR that does this at some point soon.

**Comment by The-Minecraft-Scientist** [comment]
Edit: this is a lot less feasible than I thought. I ended up adding a feature flag for it in my fork.

**Comment by ikatson** [comment]
@The-Minecraft-Scientist would happily accept a PR where it's guarded by a feature flag
