### ISSUE TITLE
use pwritev and preadv on linux

### ISSUE THREAD

**Issue by milahu** [ikatson/rqbit#144]
https://docs.rs/tokio-file/latest/tokio_file/trait.AioFileExt.html#method.writev_at

https://docs.rs/tokio-file/latest/tokio_file/trait.AioFileExt.html#method.readv_at

https://github.com/rust-lang/rust/issues/71055

https://github.com/vimpunk/cratetorrent/blob/master/DESIGN.md#vectored-io

https://old.reddit.com/r/rust/comments/kiah3q/i_wrote_cratetorrent_a_bittorrent_engine_in_rust/

https://github.com/vimpunk/cratetorrent/pull/95

**Comment by ikatson** [comment]
Blocks are not buffered in memory but dumped straight to disk. Once all are written, the data is validated.
This has a nice property of not taking any memory. In fact, the only extra memory taken is the peer read buffer which is static per peer.

This was working well so far and is simple enough. However recently I added [a storage trait](https://github.com/ikatson/rqbit/blob/main/crates/librqbit/src/storage/mod.rs#L78) where you can do whatever else - e.g. buffer (cache) blocks and write them with pwritev to reduce system calls.

That extra complexity and extra memory taken though should be justified - and I haven't seen yet why it would.
