### ISSUE TITLE
How to manually add trackers in librqbit

### ISSUE THREAD

**Issue by WZY1999428** [ikatson/rqbit#147]
Hello, I want to use librqbit to develop a small tool. I don’t see how to add trackers in the documentation. Can I add trackers manually?

**Comment by ikatson** [comment]
You can't add trackers after the torrent wasc added to the session at the moment.

The only way to add them before adding is to construct the magnet URL to have the trackers you need. 

PRs are welcome :)

**Comment by WZY1999428** [comment]
#[derive(Clone)]
struct Torrent<'a> {
    path: String,
    session: Arc<Session>,
    trackers: Vec<&'a str>,
}

impl<'a> Torrent<'a> {
    pub async fn new(path: &str) -> Self {
        Self {
            path: path.to_string(),
            session: Session::new("file".into()).await.unwrap(),
            trackers: vec![
                "udp://tracker.opentrackr.org:1337/announce",
                "udp://open.demonii.com:1337/announce",
                "udp://tracker-udp.gbitt.info:80/announce",
                "udp://open.stealth.si:80/announce",
                "https://tracker.gbitt.info:443/announce",
                "http://tracker.gbitt.info:80/announce",
                "udp://tracker.torrent.eu.org:451/announce",
                "udp://open.u-p.pw:6969/announce",
                "https://tracker.renfei.net:443/announce",
                "http://tracker.renfei.net:8080/announce",
                "udp://tracker.0x7c0.com:6969/announce",
                "udp://opentracker.io:6969/announce",
                "udp://exodus.desync.com:6969/announce",
                "https://tracker.tamersunion.org:443/announce",
                "udp://tracker.tryhackx.org:6969/announce",
                "udp://tracker.bittor.pw:1337/announce",
                "udp://tamas3.ynh.fr:6969/announce",
                "udp://run.publictracker.xyz:6969/announce",
                "udp://retracker.lanta.me:2710/announce",
                "udp://open.dstud.io:6969/announce",
            ],
        }
    }

    pub async fn add_torrent(&mut self, magnet: &str) {
        let mut url = magnet.to_string();
        for tracker in self.trackers.iter() {
            url.push_str(format!("&tr{}", tracker).as_str());
        }
        println!("{:?}", url);

        let opt = AddTorrentOptions {
            overwrite: true,
            ..Default::default()
        };
        let _managed = self
            .session
            .add_torrent(AddTorrent::from_url(url), Some(opt))
            .await
            .unwrap()
            .into_handle()
            .unwrap();
        loop {
            if let Some(d) = self.session.get(0) {
                println!("{:?}", d.get_total_bytes());
                println!("{:?}", d.stats().progress_bytes);
                if d.stats().finished {
                    break;
                }
            }
            tokio::time::sleep(tokio::time::Duration::from_secs(1)).await;
        }
    }
}
Is this how you add it?

**Comment by WZY1999428** [comment]
![image](https://github.com/ikatson/rqbit/assets/48763949/93807042-d5bb-4197-a98a-e0f7929c9791)
Hi, I use https://cdn.jsdelivr.net/gh/ngosang/trackerslist@master/trackers_all.txt. If the trackers here are udp, they will panic.

**Comment by ikatson** [comment]
I think this was fixed quite a while back, but not released.
You'll need to compile from source (e.g. use the git path in your Cargo.toml instead of 5.6.4)
