### ISSUE TITLE
webui shows undefined instead of TB traffic unit

### ISSUE THREAD

**Issue by milahu** [ikatson/rqbit#148]
the webui fails to show the terabyte unit of upload traffic
probably also fails on the petabyte unit

also, for consistency with speed units
the traffic units should be iec-i units: KiB MiB GiB TiB PiB ...

also, nitpick: add space before `(`

```
torrent 66: ↑ 0.49 MiB/s(4.31 undefined)
torrent 0: ↑ 0.00 MiB/s(6.45 GB)
torrent 8: ↑ 0.00 MiB/s(218.9 MB)
torrent 148: ↑ 0.00 MiB/s(320 KB)
torrent 18: ↑ 0.00 MiB/s
```

expected

```
$ function t() { curl -s http://localhost:3030/torrents/"$1"/stats/v1 | jq .uploaded_bytes | tee /dev/stderr | numfmt --to=iec-i --suffix=B --format=%.3f; }

$ t 66
4744189414774
4.315TiB

$ t 0
6928358881
6.453GiB

$ t 8
229536704
218.904MiB

$ t 148
327680
320.000KiB

t 18
0
0.000B
```

**Comment by ikatson** [comment]
PR's are welcome. It's a one-line fix here https://github.com/ikatson/rqbit/blob/main/crates/librqbit/webui/src/helper/formatBytes.ts#L5

**Comment by ikatson** [comment]
Fixed in https://github.com/ikatson/rqbit/pull/156
