### ISSUE TITLE
Can't add magnet or torrents on 6.0.0 beta 2 for Windows

### ISSUE THREAD

**Issue by Pentaphon** [ikatson/rqbit#154]
```
Error listing torrent files
invalid args `opts` for command `torrent_create_from_url`: missing field `paused`
```
Keep getting this message.

**Comment by ikatson** [comment]
Is this on desktop app or somewhere else?

**Comment by Pentaphon** [comment]
> Is this on desktop app

this, yes

**Comment by Pentaphon** [comment]
> Is this on desktop app or somewhere else?

@ikatson still an issue with 6.0.0

![Screenshot_11-8-2024_2194_tauri localhost](https://github.com/user-attachments/assets/e4628283-0d08-46cb-b8f0-1962e414539d)
