### ISSUE TITLE
rqbit is downloading the files within the torrent's directory and not the directory with the files within. 

### ISSUE THREAD

**Issue by Xygyl** [ikatson/rqbit#161]
Let's say that I'm downloading "1.torrent" and that it has this structure:

1/
└─a

If I download this to '~/Downloads', then I would expect to see this:

~/Downloads/
└─ 1/
      └─ a

But instead, I see this:

~/Downloads/
└─a

Is this the intended behavior? If so, is there a way for me to get the outcome in the second example?

Thank you very much.

**Comment by ikatson** [comment]
> Let's say that I'm downloading "1.torrent" and that it has this structure

I think your assumption here is wrong. If the torrent really did have this structure, it would have downloaded exactly how you wanted.

In the torrent each file looks smth like this "foo/bar/baz.ext". In your example however, the only present file looks like "a", and NOT "1/a".

However, given this, what you seem to want is for torrents **always** to be downloaded to a separate subfolder of their own.

This currently happens only if there are more than 2 files, [here's the code](https://github.com/ikatson/rqbit/blob/76083be2865c2dbf78099ba6b39d1f302f34cb46/crates/librqbit/src/session.rs#L993).

So, today, the only way to make it work like you want for torrents that contain only 1 file is to explicitly specify "subfolder" parameter (present in API). Web and Desktop UI don't let you do that, but they let you specifiy the full output folder instead.

The intention with "len < 2" was that it seemed useless to create another indirection (folder) for 1-size torrents, and I wouldn't want to remove this default behavior, as I don't see benefits, only downsides (more clicks to reach the needed file, longer paths).

But if you want, I'll accept a PR which adds an optional parameter that lets you bypass the "len < 2" check. Probably making it a Session property would be best: then in Desktop app, you can make it a permanent setting, and you can set it once from the CLI when launching the server. Smth like "always_create_subfolder"

**Comment by Xygyl** [comment]
The structure in my original post was only to serve as a simple example, the behavior persists regardless of the number of files in the torrent's directory. For example, I tried to download the tails linux .IS0 which has a structure that looks like this:

tails-amd64-6.5.img
├─ tails-amd64-6.5.img
└─ tails-amd64-6.5.img.sig

The same behavior persisted despite the number of files being two. I also tested torrents with directories that contained thirty files, though the same behavior persisted. Is there something I'm missing?

For transparency, this is the command that I'm running; 'rqbit download -o . -e tails-amd64-6.5.img.torrent'

Thank you for your time.

**Comment by ikatson** [comment]
Thanks for more details, that explains it now.

The quirk is in you using "rqbit download" rather then "rqbit server start" or any other way to download (web API, desktop etc).

"rqbit download" overrides the output folder per torrent rather than setting it per session. In this case it overrides all the logic I linked above.

Created a fix - https://github.com/ikatson/rqbit/pull/164

**Comment by Xygyl** [comment]
Thank you very much! Once this gets implemented in a release I can finally switch completely from aria2.

**Comment by ikatson** [comment]
@Xygyl did you run it to check if it helps in your case?

**Comment by Xygyl** [comment]
It worked perfectly. My gratitude is more than my words can express. Thank you very much!

**Comment by ikatson** [comment]
@Xygyl released 6.0.0 today :)

**Comment by disketten** [comment]
I have this problem when adding torrents through the HTTP API:
```bash
curl --data-binary @foo.torrent 'http://127.0.0.1:3030/torrents?output_folder=/downloads'
```

This gives me this folder structure:
```bash
/downloads $ tree
.
├── a
└── b
```

but I expected this structure:
```bash
/downloads $ tree
.
└── foo
    ├── a
    └── b
```

If I instead use `sub_folder`:
```bash
curl --data-binary @foo.torrent 'http://127.0.0.1:3030/torrents?sub_folder=foo_folder'
```
I get this structure:
```bash
/downloads $ tree
.
└── foo_folder
    ├── a
    └── b
```

but I expected this structure:
```bash
/downloads $ tree
.
└── foo_folder
    └── foo
        ├── a
        └── b
```

I'm starting rqbit with `rqbit server start /downloads`.

**Comment by ikatson** [comment]
Works exactly as expected. If you want a top level folder on downloads, just don't provide neither output folder or subfolder

**Comment by disketten** [comment]
Okay, but I would expect/like if I could put my files in different categories ("labels" in `rutorrent`) like this:
```
/downloads/Foo
/downloads/Bar
/downloads/...
```
So if I add a torrent with `sub_folder`
```bash
curl --data-binary @foo.torrent 'http://127.0.0.1:3030/torrents?sub_folder=Bar'
```
I would get
```
/downloads/Bar/foo/a
/downloads/Bar/foo/b
```

**Comment by ikatson** [comment]
It works as intended. The intention was to completely override where the torrent is downloaded. If you don't provide anything at all, the folder is inferred from torrent name. If you do provide something (either output folder per torrent, or subfolder), that exact folder is used, nothing is inferred.

In your case, just set sub_folder=Bar/foo.
Changing how this works would be unnecessary API breakage. Feel free to offer a PR to change it in a way that wouldn't break existing API users, but would still infer one more level down to the one you specified.
