### ISSUE TITLE
Identifier `v6.0.0` is both a git tag and a branch

### ISSUE THREAD

**Issue by kpcyrd** [ikatson/rqbit#165]
hi! :)

I noticed it's currently not possible to use this download link:
```
https://github.com/ikatson/rqbit/archive/v6.0.0/rqbit-6.0.0.tar.gz
```
Because there's both a branch and a tag with that name, so the identifier is not canonical.

Maybe the branch could be renamed to `v6.0.X` or `v6.X`.

Thanks!

**Comment by ikatson** [comment]
Thanks for the report, branch wasn't necessary, the tag is the source of truth, deleted the branch. Thanks!
