### ISSUE TITLE
Using librqbit with rocket will output an error message

### ISSUE THREAD

**Issue by WZY1999428** [ikatson/rqbit#166]
Hello, I use librqbit and rocket to write a remote download tool, but it outputs a lot of connection error messages. Can I disable these outputs?  
![image](https://github.com/user-attachments/assets/dc818b86-78a2-45ac-998a-ea2d5b8d3de6)

**Comment by ikatson** [comment]
Librqbit just uses the tracing library under the hood. 

It doesn't print logs on its own though, I guess that rocket does it, so you'll need to explore how to configure logging in rocket.

**Comment by WZY1999428** [comment]
Ok, I'll find out how to configure it.
