### ISSUE TITLE
Not realease the using of File after finising download

### ISSUE THREAD

**Issue by 623059008** [ikatson/rqbit#17]
OS: Windows

It happens but I don't know if it always happens.
After download finished, the progress is 100% and the remain of download is 0, the server is still using the file so users can not open the file unless close the rqbit server.

**Comment by ikatson** [comment]
Hey I think I fixed it in https://github.com/ikatson/rqbit/commit/e1a3f86a24824ac0aaf5fee6e34038374a6a6d88, but can't validate if it works cause I have no Windows access. Feel free to reopen if it doesn't work
