### ISSUE TITLE
Stop a torrent

### ISSUE THREAD

**Issue by azr** [ikatson/rqbit#18]
Hello! Nice project here !

I'm considering contributing here, but I want to ask first !
Are you even considering this ? If so, how would you go about to stop a torrent ?
Or to pause or limit the speed on a torrent's upload or download.

Cheers !

**Comment by ikatson** [comment]
@azr I'm not actively working on rqbit no longer, so not planning to do this, but would happily review the pull request if you have one. Thanks!

**Comment by ikatson** [comment]
This was done recently. You can pause or delete a torrent now, see https://github.com/ikatson/rqbit/releases/tag/v4.0.0-beta.0
