### ISSUE TITLE
Add new method `need_more_data` to `TorrentStorage`

### ISSUE THREAD

**Issue by cocool97** [ikatson/rqbit#190]
Hey ! 

What are your thought about adding a new method
`fn need_more_data(&self) -> Result<bool>;` to the `TorrentStorage` trait to let a storage decide if it need more data / can't handle new data yet from seeders ?

This would be especially useful when dealing with streaming, to control more finely the RAM amount that can be use e.g

**Comment by ikatson** [comment]
I'm not sure I understand the motivation. Say the disk is full, what do you think should happen given this trait instead of just erroring on write and pausing the torrent that happens today?

**Comment by cocool97** [comment]
I don't think that full disk is the best opportunity to illustrate this method.

A clearer use case would be to let downloader (or streamer) the opportunity to control the torrent download process without having to pause/resume it all the time. 

Saying "I don't need more data" would just interrupt the download process until consumers (watchers) consume more data to free space into storage to let the downloader download from peers

**Comment by ikatson** [comment]
won't do this, at least in the form described so far. TorrentStorage isn't a good place for hooks like this
