### ISSUE TITLE
Incorrect Linux persistent data folder name

### ISSUE THREAD

**Issue by Discreater** [ikatson/rqbit#252]
Here is my folder name
```shell
❯ ls ~/.local/share/session
721ecdc0d62e219a32e81d4fc6da00f9e1f0066f.bitv  721ecdc0d62e219a32e81d4fc6da00f9e1f0066f.torrent  session.json
```

Rqbit uses the 'directories' library. As described in its [documentation](https://docs.rs/directories/latest/directories/struct.ProjectDirs.html#examples), under Linux, only the last `application` parameter is used as the directory name. However, in rqbit,  'session' and 'dht' are used as `application` .

**Comment by ikatson** [comment]
Addressed in #253 . The old paths will be migrated to the new ones on first run.
