### ISSUE TITLE
Feature request: Auto add torrent to download if the infohash requested is not in the torrent list

### ISSUE THREAD

**Issue by sgmihai** [ikatson/rqbit#259]
I want something like mpv http://my-server.com/torrents/dd8255ecdc7ca55fb0bbf81323d87062db1f6d1c/playlist to be all that's need to play me any torrent out there.
This, together with the previous feature request I made to allow infoHash input for torrent add, would skip the extra step needed, POST-ing magnet link before requesting torrent stream/download via API, and would turn the client into a hassle free one shot torrent to http proxy.
Maybe add this as an opt in, or maybe make a separate api endpoint for this feature.
Another good addition to this would be the option that for torrents added this way (via a /stream request), to make them ephemeral, by default or choice, so that if not accessed in some period, like 2 weeks, they get deleted. But of course this would require larger changes to code base.
Hope you like the idea.

**Comment by ikatson** [comment]
If we had ephemeral streaming, this would make more sense, but until we don't this would bring more trouble than its worth. I don't think it belongs to core rqbit, at least yet.
