### ISSUE TITLE
Rust API interface

### ISSUE THREAD

**Issue by pierrbt** [ikatson/rqbit#26]
Hello, have you already made an interface to interact with the library, using rust link directly or HTTP ? If no, I'll make it myself because I need to interface it with an application made with Tauri

**Comment by ikatson** [comment]
Hi, @pierrbt, check out how [main.rs](https://github.com/ikatson/rqbit/blob/main/crates/rqbit/src/main.rs#L297) works, it's just a wrapper around either the HTTP client or around librqbit's internals, which you can reuse in a similar manner.

If this doesn't suit your needs feel free to fire a PR, thanks!

**Comment by pierrbt** [comment]
Oh thank you, I'll try to deal with this, can you juste explane me how I can make this, I'm new to Rust and I have know Idea how to import this library, and make it works. Also, does it support download resume ?

**Comment by ikatson** [comment]
It does support resume (with --overwrite option), but you can't pause or stop torrents, unless you quit / terminate the server.

**Comment by ikatson** [comment]
As for how to use it, because the crates are not exported to crates.io, you need to make it a git submodule or vendor it inside somehow (i.e. copy the rqbit source contents into your project).
Then in your code you can do smth similar to what main.rs does.
