### ISSUE TITLE
File path in the response

### ISSUE THREAD

**Issue by markolo25** [ikatson/rqbit#262]
Hi i'm currently working on radarr integration, and need a datapoint for the file path the file is saved in.

**Comment by markolo25** [comment]
The same file path provided when posting a torrent would work, if i can get it in the get torrent/id route

**Comment by ikatson** [comment]
Feel free to add a PR that adds output_folder to TorrentDetailsResponse

**Comment by markolo25** [comment]
will do

**Comment by markolo25** [comment]
Performed in https://github.com/ikatson/rqbit/pull/263
