### ISSUE TITLE
Add Open Magnet Link and change Torrent Client Info

### ISSUE THREAD

**Issue by ronovar** [ikatson/rqbit#264]
Hi,

i just downloaded application and is fantastic, easy to use and with moder gui using low hw resources. Nice done!

I have request if you can add the following features:

1. When user click in EDGE browser on magnet link, popup shows and when you click open magnet link in torrent application it needs to opet rqbit and start downloading magnet torrent. (Now you need manually to copy magnet link from web browser and paste into application, this is time consuming and it is not user friendly)
2. Add in settings windows to change torrent client info (as many private trackers allows only qBitorrent v1.34 for example for down/up torrents so without sending torrent client info to private server torrent will not download, just add box torrent client info and that user can change it. Default value will be rqbit
3. 3. Add RSS feed at left of corner so when user add xml url it can get rss feed of new torrents that can download from rss feed.

Thanks and keep that good looking and performance very good.

**Comment by ikatson** [comment]
The first one is a good request, it doesn't work not just in edge browser, it's just in general the desktop app doesn't register itself as the handler for .torrent files. Maybe someday.

The second one - won't do. There's a good reason the private trackers don't allow other clients - they know qbittorrent works exactly as they need it to work. rqbit doesn't work with private trackers yet afaik.

Third one - won't do, it's too much and out of scope of what I think rqbit should be, at least for now.
