### ISSUE TITLE
[feature request] api route to retrieve all torrents and all stats

### ISSUE THREAD

**Issue by markolo25** [ikatson/rqbit#266]
Currently in the radarr implementation 3 calls are made to retrieve all the information 

GET /torrents  - to get a list of all the torrents that exist

then we call 
/torrents/{index or hash_info} for each of the torrents 
and 
/torrents/{index or hash_info}/stats for each of the torrents 

can a GET /torrents?detailed=true be created in order to retrieve all the required infromation at once? 
or maybe a /torrents/all

**Comment by markolo25** [comment]
Another possibility is to create an /api routes since it seems /torrents was originally used for the web-ui and these routes can be used for integrations to avoid collisions with web/desktop-ui  functions.

**Comment by ikatson** [comment]
I'd vote for /torrents/stats to stay consistent. It could return a Json list with infohashes, stats etc

**Comment by ikatson** [comment]
@markolo25 can you check this PR https://github.com/ikatson/rqbit/pull/268
