### ISSUE TITLE
Download in a specific path

### ISSUE THREAD

**Issue by pierrbt** [ikatson/rqbit#27]
Is there any way to tell the HTTP API where to download the torrent, because in my case, I would like to download multiple torrents at a time, but the files get in the same directory so it's not possible to split them, I would like to download them in specific folders, is this possible ?

**Comment by ikatson** [comment]
@pierrbt , I think it's possible already, you can override "output_folder" and "sub_folder" per torrent. "output_folder" is required when starting the server, so that it has a default, but it's still overridable, both through HTTP API and CLI.
