### ISSUE TITLE
Simple auth to replace transmission-daemon

### ISSUE THREAD

**Issue by Tsai002** [ikatson/rqbit#273]
Currently, rqbit lacks built-in support for simple authentication, making it challenging to secure access to the daemon without relying on external tools or reverse proxies. Adding a straightforward username and password authentication mechanism would greatly enhance the usability and security of rqbit for users who need basic access control.

**Comment by ikatson** [comment]
> greatly enhance the usability and security

This might be a bit of an overstatement, at least without TLS :) But agree there is some value in it. Do you propose to wrap the whole API into basic auth, or leave ability to do read-only calls without authentication?

**Comment by ikatson** [comment]
@Tsai002 can you check if https://github.com/ikatson/rqbit/pull/279 is good enough
