### ISSUE TITLE
Publish Librqbit as a library on Crates.io

### ISSUE THREAD

**Issue by ALEZ-DEV** [ikatson/rqbit#31]
Hey, great work here !
I want to use your library (librqbit) part of your client to implement it in my project, do you allow me to take it for my project ? (Of course, this project will be credited)
I think it can be cool to release the librqbit part as a library on Crates.io to let people simply use it with cargo, if you allow it.

**Comment by ikatson** [comment]
Hey @ALEZ-DEV, thanks for kind words.
As per the license, you can totally use it in your project as you see fit.

As for publishing librqbit on crates.io, I think it would be better for me as the owner to do it. There's a bunch of internal crates and I guess all of them need to be published for it to work. I'll try to do this today

**Comment by ALEZ-DEV** [comment]
Thank for your quick reply.

> I'll try to do this today

That's okay, take your time.
Just notify me when the crate is published

**Comment by ALEZ-DEV** [comment]
Thank !
