### ISSUE TITLE
Load torrents from folder

### ISSUE THREAD

**Issue by crisidev** [ikatson/rqbit#40]
I quickly checked the code and I don't think this is currently supported..

I would like to allow rqbit to listen to filesystem notifications on a folder and automatically add torrents or magnet links from this folder.

If you are ok with this feature, I am happy to contribute with a PR..

**Comment by ikatson** [comment]
Hey @crisidev, it's not obvious to me why this would be useful, I assume something like this exists in other clients? Can you elaborate on a use-case, and describe how you see it implemented from the UX perspective?

PRs are very welcome, but I don't understand the need for this feature, so would appreciate if you shed some light on it.

**Comment by ikatson** [comment]
Sounds useful, so, yes happy to see a PR for this feature. Thanks!

**Comment by ikatson** [comment]
https://github.com/ikatson/rqbit/pull/237 done here
