### ISSUE TITLE
cargo tauri dev wont import rqbit-webui-src on windows. and possible solution.

### ISSUE THREAD

**Issue by Kaphar** [ikatson/rqbit#51]
I followed the [DEV-GUIDE.md](https://github.com/ikatson/rqbit/blob/main/DEV-GUIDE.md) (many thanks for that !)
when I run cargo tauri dev
the app fails to import from './rqbit-webui-src/...'
in the code for /rqbit-webui-src we have a text file without extension containing:  '../../crates/librqbit/webui/src/'
if we do a multi file search and replace './rqbit-webui-src'  -> '../../crates/librqbit/webui/src' the app runs ok.

Many thanks for sharing !

**Comment by ikatson** [comment]
thanks for the report. It seems symlinks don't work on Windows. I'll see if I can change it to not use symlinks

**Comment by ikatson** [comment]
@Kaphar I removed the symlinks here https://github.com/ikatson/rqbit/commit/29c2db1ab4c801dd0107380baf973c7b5699e4c5

Works on OSX, can you please check on Windows?

**Comment by Kaphar** [comment]
**Seems to work on windows as well !**

- Another thing that would be nice, **when we add the torrents by magnets we need to wait for the metadatas to have loaded before selecting the files and adding the torrent to the list.** _on dying torrents this could take hours_, it would be nice to be able to already list the torrent even while waiting for the metadatas, with an option to download all the files as soon as metadata is loaded, or a mode to  ask for file Selection in modal modal that needs to be user check before starting the torrent.

- Also a button to select/deselect all the files in the torrent would be nice. Or an ergonomic directory tree with selection by subdirectory. Sometimes there are 5465 files and ones wants only a few. 

-   A right click menu option in the torrent list to open the file explorer at the file location. 

Love your project! I came because I had and idea to try to load some webressources for the browser by torrent but I could definetely even use it instead of qbittorent as my torrent client.
