### ISSUE TITLE
Deselect all files for web menu

### ISSUE THREAD

**Issue by kirawi** [ikatson/rqbit#57]
I think it would make it less tedious if you're only looking for one file out of many. Currently using https://stackoverflow.com/a/63233218 as a workaround

**Comment by ikatson** [comment]
@kirawi I've done this already on top of the new UI that @arccik is working on, will merge in the next few days

**Comment by ikatson** [comment]
This was released as part of [5.2.0](https://github.com/ikatson/rqbit/releases/tag/v5.2.0)
