### ISSUE TITLE
Add dark mode for the GUI PLS

### ISSUE THREAD

**Issue by ALEZ-DEV** [ikatson/rqbit#60]
My eyes are on fire when I use your desktop app in the dark,
I'm just like this fr :
![image](https://github.com/ikatson/rqbit/assets/38623465/82e03840-dd4a-46d4-a566-2e5cf907ae2b)
Pls add dark mode

Btw, your desktop app is really cool, good job !

**Comment by ikatson** [comment]
@ALEZ-DEV this was released as part of [v5.3.0](https://github.com/ikatson/rqbit/releases/tag/v5.3.0)

**Comment by ALEZ-DEV** [comment]
Thanks !
