### ISSUE TITLE
`index 712 out of range: Excluded(0)` error

### ISSUE THREAD

**Issue by IgnisDa** [ikatson/rqbit#66]
![image](https://github.com/ikatson/rqbit/assets/60938164/7c988264-b3c9-4801-8da3-355e9d2f7722)

I have been getting this error often when downloading a large torrent (the magnet is in the previous issue I opened).

**Comment by IgnisDa** [comment]
I got this error once before too, but I ignored it then. But looks like this is an issue in `rqbit` itself.

**Comment by ikatson** [comment]
Thanks @IgnisDa for reporting. What's your OS btw?
There's another error (#54) raised from bitvec crate. It was a source of bugs so far, maybe I should replace it with smth simpler, or just hand-code it instead for maintainability, cause it has been a black box of bugs so far.

**Comment by IgnisDa** [comment]
It's a default Ubuntu box on Hetzner.

**Comment by ikatson** [comment]
@IgnisDa could you please run with RUST_BACKTRACE=full environment variable, e.g. like this

```
RUST_BACKTRACE=full rqbit ...
```

So that the full stacktrace is displayed and we see where it's coming from.

Thanks

**Comment by IgnisDa** [comment]
I am not able to reproduce it. I was able to download the rest of the torrent without any errors.

**Comment by kevin-cgc** [comment]
I was able to reproduce it about 50% of the time with a large torrent using rqbit.exe v5.4.1 (https://github.com/ikatson/rqbit/commit/6a49ae74289d407ec12374de946a928e4df0db6f) but couldn't figure out how to get symbols for the backtrace.

I rebuilt on main (c8189de3d2b132ffcd0857d961b2b78b784ad8a9) and was able to repro again on the debug build. See full backtrace: [rqbit_backtrace.txt](https://github.com/ikatson/rqbit/files/13999149/rqbit_backtrace.txt)

Key error line I guess is `rqbit\crates\librqbit\src\torrent_state\live\mod.rs:1232` but it's not immediately obvious to me why `next` is out of range.

Let me know if I can provide any more info.

--

The `.pdb` file from the windows build might be something good to upload as an Artifact in the GH action for retention to allow recovering the src line from the backtrace without rebuilding.

Thanks for your work on this project, it's been exactly what I wanted (and easy to build even on windows :).

**Comment by ikatson** [comment]
Thanks @kevin-cgc for debugging this, the backtrace you attained helps a lot! Looking if I can figure out what's going on, it's not immediately obvious either. Will try to workaround somehow

**Comment by ikatson** [comment]
@kevin-cgc could you please try again on main with #76 merged? 

I think I found the bug - the "on_have" callback didn't initialize the previously_requested_pieces bitfield. Peers rarely start with "have" instead of "bitfield", but sometimes they do.

I removed previously_requested_pieces entirely as it was unused.
