### ISSUE TITLE
Selecting custom folder for downloading

### ISSUE THREAD

**Issue by clowzed** [ikatson/rqbit#75]
Firstly, thanks for that great app!

I am using rqbit on my rpi connected to router. Sometimes I want to connect my external hdd to rpi and download files to it. Is there possibility to dynamically choose destination folder? If my question is unclear - feel free to ping me.

**Comment by clowzed** [comment]
As a workaround I start server with /dev/sda1 as I have no other disks connected, but this feature can still help someone.

**Comment by ikatson** [comment]
> Is there possibility to dynamically choose destination folder?

The "output_folder" parameter can always be set per-torrent though HTTP API, CLI or Web UI, and it'll completely override the server's default.

However, if what you mean is to change the default output folder on an already running server, this doesn't exist today. This shouldn't be hard to implement if you need it:
1. Wrap [session.output_folder](https://github.com/ikatson/rqbit/blob/main/crates/librqbit/src/session.rs#L170) into a Mutex
2. Expose changing it in [api.rs](https://github.com/ikatson/rqbit/blob/main/crates/librqbit/src/api.rs) and [http_api.rs](https://github.com/ikatson/rqbit/blob/main/crates/librqbit/src/http_api.rs)
3. Optionally, add something to Web UI to change it
