### ISSUE TITLE
Support magnet links that contain trackers with DHT disabled

### ISSUE THREAD

**Issue by av-gal** [ikatson/rqbit#80]
Magnet links may contain (a list of) trackers. Most magnet links don't contain any, relying solely on the DHT to find peers. 

The current process for adding magnet URLs always bails if DHT is disabled, because it assumes that it will not be able to retrieve the torrent's metainfo without the DHT feeding it peers. Rqbit currently doesn't contact trackers until we've checked the torrent and it knows how many bytes left to report to the tracker.

Querying a tracker only uses the infohash, and would provide peers which we could try to download the metadata from. It's safe to report we haven't uploaded or downloaded anything yet, because this magnet still hasn't been added.

**Comment by ikatson** [comment]
Thanks for very detailed and well written issues (also #79). Agree that both would be worth implementing.
I'd be happy to merge pull requests on them, let me know if there's any interest.
Otherwise maybe someday I'll get to it, too busy these days
