### ISSUE TITLE
How can I set a new path for DHT?

### ISSUE THREAD

**Issue by marcosrosse** [ikatson/rqbit#82]
Hello 👋🏿 

Can I set a new path for the DHT? I'm using this command to run the rqbit:

`rqbit --http-api-listen-addr 0.0.0.0:3030 server start --persistence-filename /app/session/session.json /app/downloads`

I'm building a Dockerfile with compose, and I would like to:
- Change the DHT path
- Adjust the log level to warn or error, if possible.

**Comment by ikatson** [comment]
Hi,

1. This isn't exposed via CLI args right now
2. Adjust the log level to warn or error:  "rqbit -v warn" should work, or RUST_LOG=warn

**Comment by ikatson** [comment]
Btw as all those dirs (both for session and DHT) are setting using "directories" crate, I guess you can try setting XDG_CONFIG_HOME to whatever you want (e.g. "/app" in your case), and then all those files will be placed there

**Comment by marcosrosse** [comment]
Hi,

Thanks for your reply! I'll try with this variable.

Also, I opened a pull request to add a Dockerfile https://github.com/ikatson/rqbit/pull/84.
