### ISSUE TITLE
rqbit client download ETA goes wonky?

### ISSUE THREAD

**Issue by psyv282j9d** [ikatson/rqbit#92]
while pulling x.AI's Grok model from the magnet link, the ETA occasionally goes wonky:
```
2024-03-19T14:43:35.322460Z  INFO rqbit: [0]: 37.95% (112.47Gi / 296.38Gi), ↓1.58 MiB/s, ↑1.12 MiB/s (1.08Ti), ETA: 107.652s, {live: 68, queued: 0, dead: 35909}
```

Clearly, at 1.6MB/sec, I'm not going to get ~180GB in 107 seconds...

Once it got down to zero, it began producing sane estimates again:
```
2024-03-19T14:45:34.456928Z  INFO rqbit: [0]: 37.95% (112.47Gi / 296.38Gi), ↓1.31 MiB/s, ↑1.01 MiB/s (1.08Ti), ETA: 619ms, {live: 65, queued: 0, dead: 35918}
2024-03-19T14:45:35.457816Z  INFO rqbit: [0]: 37.95% (112.47Gi / 296.38Gi), ↓1.30 MiB/s, ↑1.14 MiB/s (1.08Ti), ETA: 145349.588s, {live: 71, queued: 0, dead: 35910}
2024-03-19T14:45:36.459205Z  INFO rqbit: [0]: 37.95% (112.47Gi / 296.38Gi), ↓1.33 MiB/s, ↑1.12 MiB/s (1.08Ti), ETA: 141931.725s, {live: 71, queued: 0, dead: 35908}
```

Questions:

1) Does 1.3MIB/sec sound sane?  I don't use torrents often, so I don't have a sense.  My ISP connection is 300Mbit bidirectional, and this server is connected to a Ubiquiti gateway via 10Gbit fiber link.  I've not permitted upnp or any port forwarding, so maybe I'm being penalized?

2) When ETAs are large, greater than 2 minutes, would it make sense to parse it out to days/hours/minutes?

**Comment by psyv282j9d** [comment]
> That's weird, a few things
> 
> > Does 1.3MIB/sec sound sane?
> 
> Given your network and ~65 live peers, it doesn't. Did you pull 112.47Gi with that speed? It also says you uploaded 1.08Ti which is pretty insane at 1mbps. What might be happening is all those 65 peers you are connected to don't have the full torrent.

Ok, that does make sense.  I started the download within an hour after the link was posted.  At 300GB, that'll take a while to propagate.

> The ETA of 107s with that speed looks like garbage though. It was a long time since I wrote [speed_estimator.rs](https://github.com/ikatson/rqbit/blob/main/crates/librqbit_core/src/speed_estimator.rs), but by looking at it it's not immediately obvious why the numbers are so broken.

I'll take a look.

> > When ETAs are large, greater than 2 minutes, would it make sense to parse it out to days/hours/minutes?
> 
> Definitely. It's like this in UI already. I have 1GB link and never downloaded anything so large, so I never paid enough attention to the ETA counter. Here's the code if you want to make a PR https://github.com/ikatson/rqbit/blob/main/crates/rqbit/src/main.rs#L309

👍 

> Is this the magnet you are downloading? https://github.com/xai-org/grok-1 I might try to repro and see the speed, but I don't have that much space on my laptop

The one in the `README.md`, yes.

**Comment by psyv282j9d** [comment]
> > When ETAs are large, greater than 2 minutes, would it make sense to parse it out to days/hours/minutes?
> 
> Definitely. It's like this in UI already. I have 1GB link and never downloaded anything so large, so I never paid enough attention to the ETA counter. Here's the code if you want to make a PR
> https://github.com/ikatson/rqbit/blob/main/crates/rqbit/src/main.rs#L309

It seems that std::time doesn't provide `Display`, and is unmaintained.  The correct solution, per [StackOverflow](https://stackoverflow.com/questions/38957718/format-stdtime-output), is `chrono::TimeDelta` which does provide a `Display` in ISO8601 format.

I can add the dep on chrono just for that formatting, but that seems hacky to me.  thoughts?

**Comment by psyv282j9d** [comment]
> > The ETA of 107s with that speed looks like garbage though. It was a long time since I wrote [speed_estimator.rs](https://github.com/ikatson/rqbit/blob/main/crates/librqbit_core/src/speed_estimator.rs), but by looking at it it's not immediately obvious why the numbers are so broken.
> 
> I'll take a look.

hmmm, I looked it over.  I'm not sure why it's deriving the ETA from the instantaneous-ish (width of sliding window) rate.  Perhaps it would be better to calculate the ETA more simply: BPS from start * bytes_remaining

**Comment by ikatson** [comment]
The torrent download / upload speeds tend to change a lot over time, that's why it's deriving the ETA from the average speed of the last 5 seconds or so.

That's what other clients do too I guess, so I think it makes sense. 
What doesn't though is such a low ETA given such a low speed.

**Comment by ikatson** [comment]
I think I figured out what's going on. Writing down here not to forget:

the crux is here
```
// fetched can be too high in theory, so for safety make sure that it doesn't wrap around u64.
let remaining = needed
    .wrapping_sub(fetched)
    .min(needed - stats.downloaded_and_checked_bytes);
```

fetched bytes means how many chunk bytes did peers send to us. But peers fight for pieces often, so we can fetch more bytes than are needed. So the counter is slowly growing faster than necessary, and then when it wraps around, it "fixes itself".

The proper way would be to calculate remaining better - either use "downloaded_and_checked_bytes", which is a bit too coarse grained, or have smth like "written_to_filesystem_bytes", which gets subtracted from when we change the active peer for the piece.
