### ISSUE TITLE
Question: How to get the names of the files of the torrent being downloaded?

### ISSUE THREAD

**Issue by excelsiorchain** [ikatson/rqbit#93]
Problem Statement
I need assistance in finding a way to retrieve the names of the files contained within the torrent added using librqbit. Currently, I'm able to monitor download progress, but I haven't found a method or functionality within the library to fetch the file names.

Expected Behavior
I expect to find a solution or guidance on how to retrieve the names of the files within the torrent added using librqbit.

Additional Context
I couldn't find a direct method or functionality for obtaining the names of the files within the torrent. Any insights or suggestions on how to achieve this would be greatly appreciated !

Rust code:
use std::time::Duration;
use librqbit::{AddTorrent, AddTorrentOptions, Session, SessionOptions};
use log::{info, LevelFilter};
use simple_logger::SimpleLogger;
use tokio::runtime::Runtime;
fn main() {
    SimpleLogger::new().with_level(LevelFilter::Debug).init().unwrap();
    let magnet_string=String::from("magnet:?xt=urn:btih:08ada5a7a6183aae1e09d831df6748d566095a10&dn=Sintel&tr=udp%3A%2F%2Fexplodie.org%3A6969&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.empire-js.us%3A1337&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.fastcast.nz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com&ws=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2F&xs=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2Fsintel.torrent");
let mut rt = Runtime::new().unwrap();
    // Block on the asynchronous task
    rt.block_on(async {
    //tokio_test::block_on(async {
        let session = Session::new_with_opts("TorrentFolder".into(), SessionOptions {
            disable_dht: false,
            disable_dht_persistence: false,
            dht_config: None,
            persistence: false,
            persistence_filename: None,
            peer_id: None,
            peer_opts: None,
            listen_port_range: Some(10000..12000),
            enable_upnp_port_forwarding: true,
        }).await.unwrap();
        let managed_torrent_handle = session.add_torrent(
            AddTorrent::from_url(magnet_string),
            Some(AddTorrentOptions {
                paused: false,
                only_files_regex: None,
                only_files: None,
                overwrite: true,
                list_only: false,
                output_folder: None,
                sub_folder: None,
                peer_opts: None,
                force_tracker_interval: Some(Duration::from_secs(16)),
                disable_trackers: false,
                initial_peers: None,
                preferred_id: None,
            }) // options
        ).await.unwrap().into_handle().unwrap();
        //////////////////////////////////////////
        //////////////////////////////////////////
        loop {
            tokio::time::sleep(Duration::from_secs(1)).await;
            let snapshot = managed_torrent_handle.stats().live.map(|x| x.snapshot);
            let downloaded = managed_torrent_handle.live().map(|x| x.get_downloaded_bytes());
            let left = managed_torrent_handle.live().map(|x| x.get_left_to_download_bytes());
            let stats = managed_torrent_handle.stats().state;
            info!("downloaded {downloaded:?}/{left:?}, {stats}");
            info!("{snapshot:#?}");
            let raw_stats = managed_torrent_handle.stats();
            info!("raw_stats {stats}");
        }
        //managed_torrent_handle.wait_until_completed().await.unwrap();
    });
}

**Comment by ikatson** [comment]
iter_filenames_and_lengths() can be run on torrent metainfo to list all the relative filenames within.

Smth like handle.info().iter_filenames_and_lengths() in your case should do the trick.

If you need the absolute list of files on your filesystem joined with with output folder, there's no handy method for that on the handle unfortunately. PRs welcome:)
