### ISSUE TITLE
v5.5.2 is both a branch and tag

### ISSUE THREAD

**Issue by kpcyrd** [ikatson/rqbit#95]
Hello! :)

Trying to download the tarball of the latest `v5.5.2` release fails because the reference  can't be canonically be resolved:

```
the given path has multiple possibilities: #<Git::Ref:0x00007f1f31929c10>, #<Git::Ref:0x00007f1f319280e0>
```

I also noticed the github release for v5.5.1 is marked as "latest", this was probably by accident when creating the 5.5.1 release after 5.5.2.

Thanks!

**Comment by ikatson** [comment]
Hey, thanks, removed the branch

**Comment by ikatson** [comment]
> I also noticed the github release for v5.5.1 is marked as "latest", this was probably by accident when creating the 5.5.1 release after 5.5.2.

And thanks for this too, I deleted this release, it got created automatically and was not useful

**Comment by kpcyrd** [comment]
Thanks for the quick fix, the latest version is now up in Arch Linux :)

https://archlinux.org/packages/extra/x86_64/rqbit/

**Comment by ikatson** [comment]
Oh that's you just doing this right now, thanks, this is really cool!

It says that "rqbit" depends on all the GUI stuff, but I think only rqbit-desktop does, maybe it makes sense to split them up so that rqbit is just a CLI, but rqbit-desktop is the GUI app?

**Comment by kpcyrd** [comment]
You're welcome, it's a cool project! :)

This info is somewhat difficult to read these days unfortunately, only the `rqbit-desktop` package depends on the GUI libraries but since they are both built out of the `rqbit` pkgbase the GUI libraries are considered a make dependency (as noted in braces at the end):

![image](https://github.com/ikatson/rqbit/assets/7763184/10b9e299-736a-4224-a1dc-8456ca4ca257)

The cli package only depends on:

- gcc-libs
- glibc
- libssl.so

**Comment by ikatson** [comment]
Thanks for clarifying, makes sense now that these are make dependencies only
